### ISSUE TITLE
Diseño arquitectura del BackEnd

### ISSUE THREAD

**Issue by bbaruque** [danielpuente-dpg/GII14.K.QUICKTEST#12]
- [x] Diagrama de paquetes
- [x] Diagrama de clases
- [ ] Diagrama de despliege

**Comment by danielpuente-dpg** [comment]
Diagrama de clases del API - Borrador
![nuevodocumento 2017-03-02_1](https://cloud.githubusercontent.com/assets/23522200/23515971/15fbeea6-ff6c-11e6-9e34-e1e9117e8b47.jpg)

![nuevodocumento 2017-03-02_2](https://cloud.githubusercontent.com/assets/23522200/23515990/274f16f6-ff6c-11e6-89b0-8ad6bfc43fe5.jpg)

**Comment by bbaruque** [comment]
Algunos comentarios:

**Cuestionario API**

- No estoy seguro de si habría que tratar las preguntas de cada cuestionario de forma individual.
En Moodle lo hace así, pero no estoy seguro de que en nuestro caso sea necesario.
Según el modelo de datos original ¿Los cuestionarios son agregaciones de preguntas o composiciones de preguntas?

- ¿Se pretende que se puedan crear / editar las preguntas desde la app movil? En ese caso SI es probable que se necesite tratarlas de forma individual.
	
**Alumno API**

- Me parece escasa de métodos. Solo hay uno de "finalizarCuestionario()". Aquí SI se necesitaría acceder a cada pregunta, ya que se debe almacenar la respuesta de forma individual. Debe poder llamar a un metodo de contestar cada pregunta.

- ¿No hay metodos de consulta para ver resultados? AÑADIR.

**Usuario API**

Me parece correcto. No se si haría falta dar de baja un usuario, pero si no está ya esa funcionalidad, no hace falta implementarla ahora.

**Comment by danielpuente-dpg** [comment]
**Cuestionario API**

- Según el modelo de datos y la implementación, entiendo que es una composición, ya que una pregunta  no puede existir si no esta ligada a un cuestioario. Además, no existen ninguna implementación para manejar ni las preguntas ni respuestas en el controlador, salvo mediante el propio cuestionario.

- Si y no, según la implementación de partida en el controlador, la clases Custionario_CrearNuevo_Controller, permite crear y editar un cuestionario, pero internamente, tambien las preguntas y posibles respuesta. Es decir, no haria falta tratarlas de manera individual, unicamente se volveria a llamar a este metodo con el campo "IsEditar" a True y los nuevos datos y que haga el correspondiente UPDATE.

**Alumno API**

- Eso es, este método internamente, llamaria a guardarRespuesta, tantas veces como respuesta nuevas se hayan producido. Es decir, este metodo que se encuentra en Cuestionario_Resolver_Controller,  almacena cada respuesta de manera individual.

- Si, el método mostrarResultados, que se encuentra en la misma clase del punto anterior devuelve un array con toda la información pertienente

**Comment by danielpuente-dpg** [comment]
Diagrama de clases del API, hasta el momento, faltaria la clase Alumno.
![image](https://cloud.githubusercontent.com/assets/23522200/23835046/a3e2fbfa-0760-11e7-9788-13d06fdd9036.png)

**Comment by danielpuente-dpg** [comment]
Diagrama de paquetes
![image](https://cloud.githubusercontent.com/assets/23522200/23835192/568cccde-0763-11e7-92ac-c7e0d8c3dbc2.png)

**Comment by danielpuente-dpg** [comment]
Diagrama de despliege, observaciones:

- No se puede realizar al no conocer como va a ser lanzada la aplicación.
