### ISSUE TITLE
Prueba conexión Android - Moodle

### ISSUE THREAD

**Issue by danielpuente-dpg** [danielpuente-dpg/GII14.K.QUICKTEST#20]

**Comment by danielpuente-dpg** [comment]
Llevo varios días intentando comunicarme con Moodle, para intentar obtener la información pertinente a los usuarios de un determinado curso. Esta información sera utilizada para permitir iniciar sesión desde la App movil como ya comentamos en clase.
La solución encontrada es doble:

- Mediante Web services

- Mediante consultas a la propia BD de moodle.

La más interesante es la primera, por lo que se esta realizando una investigación profunda en este tema. 
He sido capaz de crear mi Web services y realizar consultas desde la propia interfaz de Moodle. Para ello he seguido varios tutoriales, el más completo es el siguiente: http://www.vitalinnova.com/servicios-web-en-moodle-2-0/

El problema es que no soy capaz de hacer un script que realice estas peticiones de forma adecuada. Tampoco se donde ubicar el script, etc. ¿Alguna posible ayuda sobre como solucionar esta problemática?

**Comment by bbaruque** [comment]
Yo también creo que la mejor opción son los servicios web.

No entiendo bien la pregunta de "donde ubicar el script". En principio ese script es solo una prueba para poder saber cómo se realiza la petición LTI a Moodle (consummer). Al final ese script se desechará y se  pasará la llamada a la app (consummer). Por eso, yo entiendo que la localización del script es indiferente.

No estoy seguro de cuál puede ser el problema, porque no indicas bien en que parte del tutorial te has quedado. ¿Has podido configurar bien tu instancia de moodle para responder a serv. web? ¿Has hecho alguna prueba (por ej. con la app oficial, accediendo a tu Moodle de pruebas)?

**Comment by danielpuente-dpg** [comment]
El tutorial le he podido finalizar correctamente e utilizar la propria herramienta que proporciona Moodle para realizar una petición de datos. Por ejemplo, indicas el token del usuario asignado al servicio web y por ejemplo le indicas que quieres obtener los datos de un usuario por Id. Y te muestra el resultado de la consulta.
Mi idea era realizar un script que realizara por ejemplo una petición similiar, pero en este caso de los alumnos. Para asi poder chequear los datos de logeo desde la App movil.
Al finaliza el tutorial, realiza en este casi una peticion REST para obtener ciertos datos, pero todo este codigo habra que almacenarlo en un script y llamarlo para la recoleccion de los datos.
Es aqui donde estoy teniendo problemas. Por que no reconoce ciertas librerias, variables que desconoce, etc.

**Comment by bbaruque** [comment]
Disculpa, pero en lugar de un script ¿No habíamos planificado hacer la llamada directamente desde una aplicación android "mock up", para comprobar cómo se podría hacer? ¿Te refieres a que es eso lo que no consigues hacer funcionar?

**Comment by danielpuente-dpg** [comment]
Eso es, he sido capaz de configurar correctamente el Web service desde Moodle. Pero ahora no se como realizar esa llamada desde la aplicación Android.
No he encontrado ningun ejemplo de Android que se comunique con los Web services de Moodle.
Lo único que he encontrado que se asemeja son ejemplos en PHP, que son como un pequeño script que realizan la petición. Y aun asi con estos últimos tengo problemas con las librerias al no encontrarlas (de ahi lo que comentaba de la ubicación del script).

**Comment by danielpuente-dpg** [comment]
En relación a lo anterior, estos pequeños scripts que comentaba, puede observar como son en el mismo link que adjunte (en el que comentaba el tutorial que habia seguido para la configuración del Web service desde Moodle). Al final del documento hay como una caja de código en una sola linea, selecciona todo el texto y pégalo en un bloc de notas y da algunos intros para mejorar la legibilidad.

**Comment by danielpuente-dpg** [comment]
Se ha podido realizar una conexión desde el entorno de virtualizacón de Android con moodle. Para ello se han seguido los siguientes pasos

- Activación de los Web services de Moodle.

- Cambio del dominio localhost a la ip de maquina.
