### ISSUE TITLE
Instalar proyecto de partida

### ISSUE THREAD

**Issue by danielpuente-dpg** [danielpuente-dpg/GII14.K.QUICKTEST#3]

**Comment by danielpuente-dpg** [comment]
https://sourceforge.net/projects/wampserver/

**Comment by danielpuente-dpg** [comment]
Buenas tardes, llevo un par de días atascado en la instalación del proyecto de partida. A continuación, intento explicar lo mejor posible el problema y la localización del mismo.

Para ello he comenzado la correcta instalación del proyecto del que  parto siguiendo los pasos indicados en la memoria, mas correctamente en la sección de  <Manual de programador>.

Toda la instalación y pasos me han funcionado correctamente hasta llegar al apartado "H. Configurar Moodle para QuickTest", en el primer punto de esa sección pide introducir unos credenciales que yo no
dispongo para continuar o desconozco. 
Es por esto que a partir de este fallo, yo no puedo continuar explorando el funcionamiento del proyecto de partida y comenzar a definir el Product backlog.

**Comment by bbaruque** [comment]
El quicktest y moodle se comunican por un protocolo que se llama LTI. Este protocolo necesitará 2 claves creo que las llama "secret" y "password" o similar.

Te dejo un enlace de consulta: https://www.imsglobal.org/activity/learning-tools-interoperability

El proceso es el siguiente:
1) Vas a quicktest y te das de alta como profesor. En ese momento te da un "secret" aleatorio y un "password" que te pide que le des tu. Supongo que en el proyecto ya habría un usuario de pruebas. Revisalo por si ya lo puedes re-utilizar. Para probarlo bien, vas a necesitar acceder a algún test de Quicktest. Si no lo encuentras, create tu propio usuario y haz un test de prueba (con 3 preguntas de prueba valdría).

2) Entras en Moodle, creas una tarea externa y en ese momento te pide: el enlace al test que se ha creado en quicktest y luego el secret y el password de tu usuario de profesor en quicktest, para poder enlazar con el recurso.

Creo que ese es el problema que indicas. Seguramente está explicado en otra sección y por eso no aparece ya en la de instalación. Revisa la documentación, por si viene detallado los pasos en otra sección anterior.

**Comment by danielpuente-dpg** [comment]
Muy buenas, ya he subsanado los errores anteriormente mencionados, muchas gracias.

Ahora la problemática a la que me estoy enfrentando es la siguiente: ¿Como accedo desde moodle como usuario (es decir, sin ser profesor entiendo yo, es decir sin esos permisos) a resolver un cuestionario que haya publicado mi profesor?

**Comment by bbaruque** [comment]
Para el usuario "alumno" debería aparecer un enlace como a cualquier otro cuestionario o recurso. 
Asegurate de que lo has marcado como "visible" (si no, solo lo ve el usuario "profesor").

**Comment by danielpuente-dpg** [comment]
Solución:

1.- Desde rol de Admin:  crear un curso, asignar un profesor y un alumno (con sus correspondientes roles) a dicho curso.
2.- Logearse como profesor e iniciar sesion y crear en enlace al cuestionario.
3.- En función del rol con el que inicies sesión, el propio sistema LTI detecta tu rol y tu vista de resolución del cuestionario varia en función de dicho rol
