### ISSUE TITLE
Generar el product backlog

### ISSUE THREAD

**Issue by danielpuente-dpg** [danielpuente-dpg/GII14.K.QUICKTEST#4]

**Comment by danielpuente-dpg** [comment]
En la ultimo reunión decidimos que comenzará a definir el Product Backlog, es decir, las historias de usuarios.
Pero al partir de este proyecto y al tener que llevar a cabo el desarrollo en Android, las historias de usuarios van a ser las mismas o prácticamente muy parecidas, ¿Hay algún inconveniente al respecto o estoy realizando un enfoque incorrecto?

**Comment by bbaruque** [comment]
En principio pueden ser parecidas. No veo que eso sea un problema.
De todas formas, ten en cuenta que este backlog es un "borrador" y se irá modificando a lo largo de todo el proyecto.

**Comment by danielpuente-dpg** [comment]
A continuación, se citan la especificación de requisitos con el rol de profesor

- [ ] RF-P1.-El profesor deberá registrarse en QuickTest utilizando como nombre de usuario, el mismo correo que en Moodle.
- [ ] RF-P2.-Podrá iniciar sesión una vez logeado.
- [ ] RF-P3.-Podrá crear un nuevo cuestionario.
- [ ] RF-P4.-Podrá editar un cuestionario.
- [ ] RF-P5.-Podrá eliminar un cuestionario.
- [ ] RF-P6.-Podrá duplicar un cuestionario.
- [ ] RF-P7.-Podrá configurar los comodines
- [ ] RF-P8.-Podrá editar las preguntas de un cuestionario.
- [ ] RF-P9.-Podrá configurar la puntuación de cada preguntar.
- [ ] RF-P10.-Podrá elegir la respuesta correcta de cada pregunta.
- [ ] RF-P11.-Podrá cerrar sesión.
- [ ] RF-P12.-Podrá cerrar sesión y olvidar.

A continuación, se citan la especificación de requisitos con el rol de alumno

- [ ] RF-A1	El alumno deberá registrarse en QuickTest utilizando como nombre de usuario, el mismo correo que en Moodle.
- [ ] RF-A2	El alumno podrá iniciar sesión una vez logeado.
- [ ] RF-A3	Podrá responder al cuestionario.
- [ ] RF-A4	Podrá decidir si usar los comodines.
- [ ] RF-A5	Por cada pregunta del cuestionario podrá guardar su respuesta.
- [ ] RF-A6	Por cada pregunta del cuestionario podrá anular la respuesta guardada.
- [ ] RF-A7	Podrá finalizar el cuestionario y acabar.
- [ ] RF-A8	Podrá guardar el estado de todas las preguntas y finalizar y acabar.
- [ ] RF-A9	Podrá cerrar sesión.
- [ ] RF-A10	Podrá cerrar sesión y olvidar.
- [ ] RF-A11	Podrá revisar sus respuestas.
- [ ] RF-A12	Podrá ver su calificación.
- [ ] RF-A13	Si el cuestionario está cerrado podrá revisarlo y ver su calificación.
