### ISSUE TITLE
Envío de respuestas desde la app a quicktest

### ISSUE THREAD

**Issue by bbaruque** [danielpuente-dpg/GII14.K.QUICKTEST#40]
- [x] Envio a QuickTest
- [ ] Quicktest permite almacenarlo en Moodle

**Comment by danielpuente-dpg** [comment]
Durante el desarrollo de este issue, me he encontrado con la siguientes problemáticas:

- Para el envió a QuickTest no hay ningún inconveniente, pero para el almacenamiento en Moodle SI. El proyecto de partida realiza esta actualización de la nota de esa herramienta externa mediante la utilización de un método denominado: "prepare_Grade_toMoodle" (en LTI_Controller). Este método es el encargado de calcular la nota y de realizar la conversión al formato que utiliza Moodle, pero en la ultimas lineas del mismo realiza una invocación al metodo: "comunicate_Grade_toMoodle_XML" (dentro de la misma clase). Este es el encargo de introducir esa nota en el apartado de calificaciones de Moodle. **Aquí es donde se produce la problemática**.  Dentro de este metodo se obtiene un contexto y sobre este se basa la logica del metodo. Si no entiendo mal, este contexto se basa en la propia sesión del navegador y al llamarlo yo, sin tener ese contexto no funciona. ¿Es eso lo que de verdad esta pasando?¿O lo estoy entendiendo mal?.

- Relacionado con lo anterior. Al ver que no disponía de esa herramienta. Indague en el Webservices de Moodle haber si hay algún método que  realice esta misma acción. La única que realiza esto y se encuentra disponible en el WebService es **mod_assign_save_grade**. Segun la documentación actualiza una calificación. Problemas: no he sido capaz de hacerla funcionar, ya que no he encontrado ningun ejemplo de uso al respecto y la propia doc de Moodle o no ayuda nada o no soy capaz de interpretarla correctamente. Frente a esta otra alternativa, ¿Donde podría encontrar algún ejemplo ? o ¿Me podría orientar un poco al funcionamiento de la misma?

**Comment by bbaruque** [comment]
Efectivamente, el standrad LTI envía al conectarse al servidor de QuickTest un objeto "context" que permite conocer la información de: Desde que asignatura se ha llamado, para que cuestionario, quien es el usuario que ha pulsado sobre el enlace, si es profesor o alumno...etc.
Yo entiendo que no es información del navegador, es información que transmite el LTI consumer (Moodle) para que el LTI producer (Quicktest) conozca información de quien le llama.
Por eso al enviar de nuevo la nota, se necesita recuperar el contexto para saber en que asignatura y cuestionario y a que alumno le corresponde esa nota.
Habrá que pedir el contexto a Moodle, de la misma forma que se le pide el token y aquí hay dos opciones:
- Almacenarlo en la app y enviarlo luego cuando se necesite esa información para el envío de la nota.
- Mandarlo directamente a Quicktest y que se procese de forma normal. Una vez finalizado el cuestionario, se envían las respuestas del usuario a Quicktest (sobreescribiendo lo que haría desde el formulario web) y dejar que él procese las notas y envíe la respuesta. 
No estoy seguro de cuál puede ser más ventajosa.

**Comment by danielpuente-dpg** [comment]
-  He incluido la funcionalidad de como añadir la calificación en Moodle en el APIRest - **sin exito**. He estado indagando mucho y sigo sin conseguir que realice esta actualización. Para llevarlo a cabo, he adaptado la funcionalidad de Alejandro de incluir la calificación en Moodle, incluyendo mi propia funcionalidad en el API, pero **sigue sin funcionar**.

- He intentando buscar otras opciones, y como venia comentado anteriormente, la única funcionalidad del web service que opera sobre las calificaciones de Moodle es la función **mod_assign_save_grade**.  Pero esta alternativa tampoco funciona. _Destacar que en la red parece ser que este tema esta muy verde_.
