### ISSUE TITLE
Implementación de los métodos de API

### ISSUE THREAD

**Issue by bbaruque** [danielpuente-dpg/GII14.K.QUICKTEST#9]

**Comment by danielpuente-dpg** [comment]
ALGUNOS PROBLEMAS:

- Algunos métodos devuelven echo en formato JSON_ENCODE y se corrompe la devolución de dichos métodos.

- El método duplicar cuestionario no existe en el controlador, se comunica directamente con el modelo. Además, existen otros métodos con el mismo inconveniente.

- ¿Como saber si el cuestionario esta terminado?¿Diferencia entre los métodos checkSegundoIntento y estaResuelto?

DUDAS

- ¿Como comunicarse con LTI_Controller?

- ¿Como saber la sesion? $_SESION (ltiCosumerURL)
